---

- include: "{{ opsmgr_lib }}/util/osa.yml"

- hosts: localhost
  gather_facts: yes

  vars:

    - recipe_name: "bcn"
    - output_dir: "profile"
    - temp_dir: "/tmp/.opsmgr-{{ recipe_name }}"
    - osa_conf: "/etc/openstack_deploy"
    - osa_play: "/etc/ansible/roles"
    - osa_home: "/opt/openstack-ansible"
    - ansible_kernel: "4.2.0-42-generic"
    - files_to_include:
        - "{{ osa_conf }}/user_secrets.yml"
        - "{{ osa_conf }}/openstack_user_config.yml"
        - "{{ osa_play }}/openstack_hosts/defaults/main.yml"
        - "{{ osa_play }}/os_horizon/defaults/main.yml"
        - "{{ osa_play }}/os_swift/defaults/main.yml"
        - "{{ osa_play }}/galera_client/defaults/main.yml"
        - "{{ osa_home }}/playbooks/inventory/group_vars/all.yml"

  pre_tasks:

    - name: run uname cmd
      local_action: command uname -r
      register: uname

    - name: set ansible_kernel value
      set_fact: ansible_kernel="{{ uname.stdout | replace('\"', '') }}"

  tasks:

    - name: imports all necessary variables
      include_vars: "{{ item }}"
      with_items: "{{ files_to_include }}"

    - name: ensures output directory exists
      become: no
      file: path={{ output_dir }} mode=0755 state=directory

    - name: create inventory
      become: no
      template:
          src: "templates/inventory.j2"
          dest: "{{ output_dir }}/inventory"

    - name: create vars
      become: no
      template:
          src: "templates/vars.yml.j2"
          dest: "{{ output_dir }}/vars.yml"

