# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
temp_install_directory: /tmp/kibana_install

kibana_directory: kibana-5.6.3-linux-x86_64
nodejs_directory: node-v6.11.1-linux-ppc64le

kibana_packages:
  - { url: "https://artifacts.elastic.co/downloads/kibana",
      file: "kibana-5.6.3-linux-x86_64.tar.gz",
      directory: "{{ kibana_directory }}",
      checksum: "sha512:fe957f0a2def9fb40be32ac77986d5eb7cc3373f828eed8eae074770ef965cf01c36028f2f9790f927e217ee59a283e63273eb768b9d2375aa0cdf15e4963c9a" }
  - { url: "http://nodejs.org/dist/v6.11.1",
      file: "node-v6.11.1-linux-ppc64le.tar.gz",
      directory: "{{ nodejs_directory }}",
      checksum: "sha1:a5e508518d1bc288aeae1582c9669cdb6216932a" }

config_dir: /opt/kibana/config
install_dir: /opt/kibana
