---

- include: "{{ opsmgr_lib }}/util/osa.yml"

- hosts: localhost
  gather_facts: yes
  become: no

  vars_files:
    - defaults.yml

  vars:

    - recipe_name: "standalone"
    - output_dir: "profile"
    - temp_dir: "/tmp/.opsmgr-{{ recipe_name }}"
    - genesis_dir: "/var/oprc"
    - osa_conf: "/etc/openstack_deploy"
    - osa_play: "/etc/ansible/roles"
    - osa_home: "/opt/openstack-ansible"
    - files_to_include:
        - "{{ osa_conf }}/user_secrets.yml"
        - "{{ osa_conf }}/openstack_user_config.yml"
        - "{{ osa_play }}/openstack_hosts/defaults/main.yml"
        - "{{ osa_play }}/os_horizon/defaults/main.yml"
        - "{{ osa_play }}/galera_client/defaults/main.yml"
        - "{{ osa_home }}/playbooks/inventory/group_vars/all.yml"
        - "{{ genesis_dir }}/inventory.yml"

  pre_tasks:

    - name: run uname cmd
      local_action: command uname -r
      register: uname

    - name: set ansible_kernel value
      set_fact: ansible_kernel="{{ uname.stdout | replace('\"', '') }}"

  tasks:

    - name: imports all necessary variables from OSA
      include_vars: "{{ item }}"
      with_items: "{{ files_to_include }}"

    - name: ensures output directory exists
      file: path={{ output_dir }} mode=0755 state=directory

    - name: figure out the right IP to use for opsmgr
      shell: ip route get {{ nodes[(nodes.keys() | list)[0]][0][opsmgr_iface] }} | awk '{print $NF;exit}'
      register: result

    - name: store it in variable for later use
      set_fact: routing_address="{{ result.stdout }}"

    - name: create inventory from template
      template:
          src: "templates/inventory.j2"
          dest: "{{ output_dir }}/inventory"

    - name: create vars file from template
      template:
          src: "templates/vars.yml.j2"
          dest: "{{ output_dir }}/vars.yml"

